<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kiosk.Domain\Kiosk.Domain.csproj" />
    <ProjectReference Include="..\..\src\Kiosk.Application\Kiosk.Application.csproj" />
    <ProjectReference Include="..\..\src\Kiosk.Infrastructure\Kiosk.Infrastructure.csproj" />
  </ItemGroup>

</Project>