/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/paymongo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"][];
                        "application/json": components["schemas"]["OrderDto"][];
                        "text/json": components["schemas"]["OrderDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/orders/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/orders/{id}/confirm-cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmCashRequest"];
                    "text/json": components["schemas"]["ConfirmCashRequest"];
                    "application/*+json": components["schemas"]["ConfirmCashRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CashConfirmationDto"];
                        "application/json": components["schemas"]["CashConfirmationDto"];
                        "text/json": components["schemas"]["CashConfirmationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CancelOrderRequest"];
                    "text/json": components["schemas"]["CancelOrderRequest"];
                    "application/*+json": components["schemas"]["CancelOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/orders/{id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pos/shift-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShiftSummaryDto"];
                        "application/json": components["schemas"]["ShiftSummaryDto"];
                        "text/json": components["schemas"]["ShiftSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MenuDto"];
                        "application/json": components["schemas"]["MenuDto"];
                        "text/json": components["schemas"]["MenuDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                    "text/json": components["schemas"]["CreateOrderRequest"];
                    "application/*+json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["KioskOrderDto"];
                        "application/json": components["schemas"]["KioskOrderDto"];
                        "text/json": components["schemas"]["KioskOrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/orders/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PayRequest"];
                    "text/json": components["schemas"]["PayRequest"];
                    "application/*+json": components["schemas"]["PayRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["KioskOrderDto"];
                        "application/json": components["schemas"]["KioskOrderDto"];
                        "text/json": components["schemas"]["KioskOrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/orders/{id}/cancel-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["KioskOrderDto"];
                        "application/json": components["schemas"]["KioskOrderDto"];
                        "text/json": components["schemas"]["KioskOrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["KioskOrderDto"];
                        "application/json": components["schemas"]["KioskOrderDto"];
                        "text/json": components["schemas"]["KioskOrderDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/orders/{id}/slip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/tables/{tableNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tableNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TableStatusDto"];
                        "application/json": components["schemas"]["TableStatusDto"];
                        "text/json": components["schemas"]["TableStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kds/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"][];
                        "application/json": components["schemas"]["OrderDto"][];
                        "text/json": components["schemas"]["OrderDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kds/orders/{id}/preparing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kds/orders/{id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kds/orders/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoardDto"];
                        "application/json": components["schemas"]["BoardDto"];
                        "text/json": components["schemas"]["BoardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceDto"][];
                        "application/json": components["schemas"]["DeviceDto"][];
                        "text/json": components["schemas"]["DeviceDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDeviceRequest"];
                    "text/json": components["schemas"]["RegisterDeviceRequest"];
                    "application/*+json": components["schemas"]["RegisterDeviceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisteredDeviceDto"];
                        "application/json": components["schemas"]["RegisteredDeviceDto"];
                        "text/json": components["schemas"]["RegisteredDeviceDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryDto"][];
                        "application/json": components["schemas"]["CategoryDto"][];
                        "text/json": components["schemas"]["CategoryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertCategoryRequest"];
                    "text/json": components["schemas"]["UpsertCategoryRequest"];
                    "application/*+json": components["schemas"]["UpsertCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryDto"];
                        "application/json": components["schemas"]["CategoryDto"];
                        "text/json": components["schemas"]["CategoryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertCategoryRequest"];
                    "text/json": components["schemas"]["UpsertCategoryRequest"];
                    "application/*+json": components["schemas"]["UpsertCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryDto"];
                        "application/json": components["schemas"]["CategoryDto"];
                        "text/json": components["schemas"]["CategoryDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderRequest"];
                    "text/json": components["schemas"]["ReorderRequest"];
                    "application/*+json": components["schemas"]["ReorderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"][];
                        "application/json": components["schemas"]["AdminProductDto"][];
                        "text/json": components["schemas"]["AdminProductDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertProductRequest"];
                    "text/json": components["schemas"]["UpsertProductRequest"];
                    "application/*+json": components["schemas"]["UpsertProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"];
                        "application/json": components["schemas"]["AdminProductDto"];
                        "text/json": components["schemas"]["AdminProductDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"];
                        "application/json": components["schemas"]["AdminProductDto"];
                        "text/json": components["schemas"]["AdminProductDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertProductRequest"];
                    "text/json": components["schemas"]["UpsertProductRequest"];
                    "application/*+json": components["schemas"]["UpsertProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"];
                        "application/json": components["schemas"]["AdminProductDto"];
                        "text/json": components["schemas"]["AdminProductDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetStockRequest"];
                    "text/json": components["schemas"]["SetStockRequest"];
                    "application/*+json": components["schemas"]["SetStockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"];
                        "application/json": components["schemas"]["AdminProductDto"];
                        "text/json": components["schemas"]["AdminProductDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/products/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetAvailabilityRequest"];
                    "text/json": components["schemas"]["SetAvailabilityRequest"];
                    "application/*+json": components["schemas"]["SetAvailabilityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDto"];
                        "application/json": components["schemas"]["AdminProductDto"];
                        "text/json": components["schemas"]["AdminProductDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/products/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderRequest"];
                    "text/json": components["schemas"]["ReorderRequest"];
                    "application/*+json": components["schemas"]["ReorderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/media/uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteMediaUploadRequest"];
                    "text/json": components["schemas"]["CompleteMediaUploadRequest"];
                    "application/*+json": components["schemas"]["CompleteMediaUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MediaDto"];
                        "application/json": components["schemas"]["MediaDto"];
                        "text/json": components["schemas"]["MediaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddMediaRequest"];
                    "text/json": components["schemas"]["AddMediaRequest"];
                    "application/*+json": components["schemas"]["AddMediaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MediaDto"];
                        "application/json": components["schemas"]["MediaDto"];
                        "text/json": components["schemas"]["MediaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    mediaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modifier-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModifierGroupDto"][];
                        "application/json": components["schemas"]["ModifierGroupDto"][];
                        "text/json": components["schemas"]["ModifierGroupDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertModifierGroupRequest"];
                    "text/json": components["schemas"]["UpsertModifierGroupRequest"];
                    "application/*+json": components["schemas"]["UpsertModifierGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModifierGroupDto"];
                        "application/json": components["schemas"]["ModifierGroupDto"];
                        "text/json": components["schemas"]["ModifierGroupDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modifier-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertModifierGroupRequest"];
                    "text/json": components["schemas"]["UpsertModifierGroupRequest"];
                    "application/*+json": components["schemas"]["UpsertModifierGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModifierGroupDto"];
                        "application/json": components["schemas"]["ModifierGroupDto"];
                        "text/json": components["schemas"]["ModifierGroupDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modifier-groups/{groupId}/modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertModifierRequest"];
                    "text/json": components["schemas"]["UpsertModifierRequest"];
                    "application/*+json": components["schemas"]["UpsertModifierRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModifierDto"];
                        "application/json": components["schemas"]["ModifierDto"];
                        "text/json": components["schemas"]["ModifierDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modifier-groups/{groupId}/modifiers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertModifierRequest"];
                    "text/json": components["schemas"]["UpsertModifierRequest"];
                    "application/*+json": components["schemas"]["UpsertModifierRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModifierDto"];
                        "application/json": components["schemas"]["ModifierDto"];
                        "text/json": components["schemas"]["ModifierDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/media/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PresignMediaRequest"];
                    "text/json": components["schemas"]["PresignMediaRequest"];
                    "application/*+json": components["schemas"]["PresignMediaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PresignedUploadDto"];
                        "application/json": components["schemas"]["PresignedUploadDto"];
                        "text/json": components["schemas"]["PresignedUploadDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesReportDto"];
                        "application/json": components["schemas"]["SalesReportDto"];
                        "text/json": components["schemas"]["SalesReportDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/refunds-needed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RefundNeededDto"][];
                        "application/json": components["schemas"]["RefundNeededDto"][];
                        "text/json": components["schemas"]["RefundNeededDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffOverviewDto"];
                        "application/json": components["schemas"]["StaffOverviewDto"];
                        "text/json": components["schemas"]["StaffOverviewDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteStaffRequest"];
                    "text/json": components["schemas"]["InviteStaffRequest"];
                    "application/*+json": components["schemas"]["InviteStaffRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffInvitation"];
                        "application/json": components["schemas"]["StaffInvitation"];
                        "text/json": components["schemas"]["StaffInvitation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff/invitations/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetStaffRoleRequest"];
                    "text/json": components["schemas"]["SetStaffRoleRequest"];
                    "application/*+json": components["schemas"]["SetStaffRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffMemberDto"];
                        "application/json": components["schemas"]["StaffMemberDto"];
                        "text/json": components["schemas"]["StaffMemberDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff/{userId}/remove-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/staff/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMediaRequest: {
            type: components["schemas"]["MediaType"];
            url: string;
            thumbnailUrl: null | string;
            /** Format: int32 */
            sortOrder: number;
        };
        AdminProductDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string;
            name: string;
            description: null | string;
            /** Format: double */
            basePrice: number;
            /** Format: int32 */
            stock: null | number;
            isAvailable: boolean;
            /** Format: int32 */
            sortOrder: number;
            media: components["schemas"]["MediaDto"][];
            modifierGroupIds: string[];
        };
        BoardDto: {
            preparing: components["schemas"]["BoardEntryDto"][];
            ready: components["schemas"]["BoardEntryDto"][];
        };
        BoardEntryDto: {
            orderNumber: string;
            diningOption: components["schemas"]["DiningOption"];
            type: components["schemas"]["OrderType"];
            /** Format: int32 */
            tableNumber: null | number;
        };
        CancelOrderRequest: {
            reason: string;
        };
        CashConfirmationDto: {
            order: components["schemas"]["OrderDto"];
            /** Format: double */
            amountTendered: number;
            /** Format: double */
            changeDue: number;
        };
        CashTotalsDto: {
            /** Format: int32 */
            orders: number;
            /** Format: double */
            cashCollected: number;
        };
        CategoryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            sortOrder: number;
            isActive: boolean;
            /** Format: int32 */
            productCount: number;
        };
        CompleteMediaUploadRequest: {
            key: string;
            type: components["schemas"]["MediaType"];
            /** Format: int32 */
            sortOrder: number;
        };
        ConfirmCashRequest: {
            /** Format: double */
            amountTendered: number;
        };
        CreateOrderLine: {
            /** Format: uuid */
            productId: string;
            /** Format: int32 */
            quantity: number;
            modifierIds: null | string[];
            notes: null | string;
        };
        CreateOrderRequest: {
            diningOption: components["schemas"]["DiningOption"];
            orderType: components["schemas"]["OrderType"];
            /** Format: int32 */
            tableNumber: null | number;
            items: components["schemas"]["CreateOrderLine"][];
        };
        DailySalesDto: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            orders: number;
            /** Format: double */
            sales: number;
        };
        DeviceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["DeviceKind"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: null | string;
        };
        /** @enum {unknown} */
        DeviceKind: "Kiosk" | "Board";
        /** @enum {unknown} */
        DiningOption: "DineIn" | "TakeOut";
        InviteStaffRequest: {
            email: string;
            role: string;
            redirectUrl: null | string;
        };
        KioskOrderDto: {
            order: components["schemas"]["OrderDto"];
            slipToken: null | string;
            checkoutUrl: null | string;
        };
        MediaDto: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["MediaType"];
            url: string;
            thumbnailUrl: null | string;
        };
        /** @enum {unknown} */
        MediaType: "Image" | "Video";
        MenuCategoryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            products: components["schemas"]["MenuProductDto"][];
        };
        MenuDto: {
            categories: components["schemas"]["MenuCategoryDto"][];
        };
        MenuModifierDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            priceDelta: number;
            isAvailable: boolean;
        };
        MenuModifierGroupDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            minSelect: number;
            /** Format: int32 */
            maxSelect: number;
            isRequired: boolean;
            modifiers: components["schemas"]["MenuModifierDto"][];
        };
        MenuProductDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            /** Format: double */
            price: number;
            isSoldOut: boolean;
            media: components["schemas"]["MediaDto"][];
            modifierGroups: components["schemas"]["MenuModifierGroupDto"][];
        };
        ModifierDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            priceDelta: number;
            isAvailable: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        ModifierGroupDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            minSelect: number;
            /** Format: int32 */
            maxSelect: number;
            isRequired: boolean;
            modifiers: components["schemas"]["ModifierDto"][];
        };
        OrderDto: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            diningOption: components["schemas"]["DiningOption"];
            type: components["schemas"]["OrderType"];
            /** Format: int32 */
            tableNumber: null | number;
            status: components["schemas"]["OrderStatus"];
            /** Format: double */
            subtotal: number;
            /** Format: double */
            taxAmount: number;
            /** Format: double */
            total: number;
            paymentMethod: null | components["schemas"]["PaymentMethod"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            paidAt: null | string;
            items: components["schemas"]["OrderItemDto"][];
        };
        OrderItemDto: {
            /** Format: uuid */
            productId: string;
            name: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            unitPrice: number;
            /** Format: double */
            lineTotal: number;
            notes: null | string;
            modifiers: components["schemas"]["OrderItemModifierDto"][];
        };
        OrderItemModifierDto: {
            name: string;
            /** Format: double */
            priceDelta: number;
        };
        /** @enum {unknown} */
        OrderStatus: "Created" | "AwaitingPayment" | "PaymentPending" | "Failed" | "Paid" | "Preparing" | "Ready" | "Completed" | "Expired" | "Cancelled";
        /** @enum {unknown} */
        OrderType: "CounterPickup" | "ServeToTable";
        /** @enum {unknown} */
        PaymentMethod: "Cash" | "EWallet" | "Card" | "QrPh" | null;
        PaymentMethodSalesDto: {
            method: components["schemas"]["PaymentMethod"];
            /** Format: int32 */
            orders: number;
            /** Format: double */
            sales: number;
        };
        PayRequest: {
            method: components["schemas"]["PaymentMethod"];
        };
        PresignedUploadDto: {
            key: string;
            uploadUrl: string;
            contentType: string;
            /** Format: int64 */
            maxBytes: number;
            /** Format: date-time */
            expiresAt: string;
        };
        PresignMediaRequest: {
            type: components["schemas"]["MediaType"];
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        ProductSalesDto: {
            /** Format: uuid */
            productId: string;
            name: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            sales: number;
        };
        RefundNeededDto: {
            /** Format: int64 */
            eventId: number;
            /** Format: uuid */
            orderId: string;
            orderNumber: string;
            /** Format: date */
            businessDate: string;
            orderStatus: components["schemas"]["OrderStatus"];
            /** Format: double */
            orderTotal: number;
            /** Format: date-time */
            at: string;
            note: null | string;
        };
        RegisterDeviceRequest: {
            name: string;
            kind: components["schemas"]["DeviceKind"];
        };
        RegisteredDeviceDto: {
            device: components["schemas"]["DeviceDto"];
            token: string;
        };
        ReorderRequest: {
            ids: string[];
        };
        SalesReportDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** Format: int32 */
            orders: number;
            /** Format: double */
            grossSales: number;
            /** Format: double */
            vatAmount: number;
            /** Format: double */
            netOfVat: number;
            /** Format: double */
            averageOrder: number;
            byPaymentMethod: components["schemas"]["PaymentMethodSalesDto"][];
            byDay: components["schemas"]["DailySalesDto"][];
            topProducts: components["schemas"]["ProductSalesDto"][];
            /** Format: int32 */
            refundsNeeded: number;
        };
        SetAvailabilityRequest: {
            isAvailable: boolean;
        };
        SetStaffRoleRequest: {
            role: string;
        };
        SetStockRequest: {
            /** Format: int32 */
            stock: null | number;
        };
        ShiftSummaryDto: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            mine: components["schemas"]["CashTotalsDto"];
            allCashiers: components["schemas"]["CashTotalsDto"];
            /** Format: int32 */
            cancelledByMe: number;
        };
        StaffInvitation: {
            id: string;
            email: string;
            role: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        StaffMemberDto: {
            id: string;
            name: string;
            email: null | string;
            role: null | string;
            imageUrl: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSignInAt: null | string;
            canManage: boolean;
            isYou: boolean;
        };
        StaffOverviewDto: {
            staff: components["schemas"]["StaffMemberDto"][];
            pendingApproval: components["schemas"]["StaffMemberDto"][];
            invitations: components["schemas"]["StaffInvitation"][];
            assignableRoles: string[];
        };
        TableStatusDto: {
            /** Format: int32 */
            tableNumber: number;
            inUse: boolean;
        };
        UpsertCategoryRequest: {
            name: string;
            /** Format: int32 */
            sortOrder: number;
            isActive: boolean;
        };
        UpsertModifierGroupRequest: {
            name: string;
            /** Format: int32 */
            minSelect: number;
            /** Format: int32 */
            maxSelect: number;
            isRequired: boolean;
        };
        UpsertModifierRequest: {
            name: string;
            /** Format: double */
            priceDelta: number;
            isAvailable: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        UpsertProductRequest: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            description: null | string;
            /** Format: double */
            basePrice: number;
            /** Format: int32 */
            stock: null | number;
            isAvailable: boolean;
            /** Format: int32 */
            sortOrder: number;
            modifierGroupIds: null | string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
